### ISSUE TITLE
Can't use file with * in the filename

### ISSUE THREAD

**Issue by mjj29** [xpybuild/xpybuild#13]
If you try and do:

Target('FileWith*InTheName')
Zip('Output', ['FileWith*InTheName'])

then you'll get the error 'can't use globs here did you mean to use FindPaths'

**Comment by ben-spiller** [comment]
Are you sure this is a bug? Instead, I think we should actually prevent illegal Windows chars like `*` from appearing in target names, since its a downright weird thing to do, and helpful for it to be prevented on Linux just as it already is on Windows

**Comment by mjj29** [comment]
In my defense when I wrote this I didn't know it wasn't allowed on windows (-:

In either case we should certainly ban it everywhere, rather than giving an obscure error only half the time

**Comment by ben-spiller** [comment]
Agreed. I've added logic to prevent * and other disallowed windows chars in basetarget.py:
badchars = '<>:"|?*'
