### ISSUE TITLE
There is no way to define a property value containing '#' in a properties file

### ISSUE THREAD

**Issue by rthrippleton** [xpybuild/xpybuild#20]
A .properties file containing
```
SOME_URL=${DOC_URL_ROOT}/mypage.html#someanchor
```
Will not parse as expected (that is, the anchor is quietly elided). There doesn't seem to be an escaping scheme that allows a '#'.

**Comment by ben-spiller** [comment]
Fixed in 55ec707c8db701f3cd1ae91bcdac5083b29c45a7
